### ISSUE TITLE
Crash when attempting to play an invalid link

### ISSUE THREAD

**Issue by BowBoy1** [EngineMachiner/HonkyTones#5]
The game crashes when an invalid link is played, when it should probably be a handled exception.
[crash-2024-03-06_19.21.10-client.txt](https://github.com/EngineMachiner/HonkyTones/files/14517107/crash-2024-03-06_19.21.10-client.txt)

**Comment by EngineMachiner** [comment]
Hello, these not found classes exceptions were caused because I had issues setting the proper dependencies when building the last build. This has been fixed and will be in the next build.
